categories = [
    {
        "name": "Sports Nutrition",
        "items": [
            {"id": 1, "name": "Clif Energy Bar", "description": "A high-energy snack with oats and chocolate chips, ideal for pre-workout fuel.", "price": 126 / 0.068, "unit": "kg"},
            {"id": 2, "name": "Quest Protein Bar", "description": "High-protein bar with cookies and cream flavor, supports muscle recovery.", "price": 210 / 0.06, "unit": "kg"},
            {"id": 3, "name": "Gatorade Sports Drink", "description": "Lemon-lime flavored drink to replenish electrolytes during intense workouts.", "price": 147 / 0.907, "unit": "kg"},
            {"id": 4, "name": "Powerade", "description": "Mountain Berry Blast flavor, hydrates and boosts energy for athletes.", "price": 134.4 / 0.907, "unit": "kg"},
            {"id": 5, "name": "Optimum Nutrition Whey Protein", "description": "Vanilla-flavored whey protein for muscle building and recovery.", "price": 2519.16 / 0.907, "unit": "kg"},
            {"id": 6, "name": "Muscle Milk Protein Shake", "description": "Chocolate shake with high protein for post-workout nutrition.", "price": 252 / 0.397, "unit": "kg"},
            {"id": 7, "name": "RXBAR Protein Bar", "description": "Peanut butter bar with natural ingredients for sustained energy.", "price": 189 / 0.052, "unit": "kg"},
            {"id": 8, "name": "Nature Valley Protein Bar", "description": "Peanut butter and dark chocolate bar, great for on-the-go nutrition.", "price": 105 / 0.04, "unit": "kg"},
            {"id": 9, "name": "Electrolyte Tablets", "description": "Nuun Sport tablets for hydration, packed with essential electrolytes.", "price": 587.16 / 0.05, "unit": "kg"},
            {"id": 10, "name": "Gatorade Zero Powder", "description": "Fruit Punch flavored powder, zero sugar, for hydration.", "price": 503.16 / 0.05, "unit": "kg"},
            {"id": 11, "name": "Kind Energy Bar", "description": "Dark chocolate nut bar, provides lasting energy for active lifestyles.", "price": 151.2 / 0.06, "unit": "kg"},
            {"id": 12, "name": "Pure Protein Bar", "description": "Chocolate peanut butter bar, high protein for muscle support.", "price": 126 / 0.05, "unit": "kg"},
            {"id": 13, "name": "BodyArmor Sports Drink", "description": "Tropical Punch flavor, packed with vitamins for superior hydration.", "price": 168 / 0.794, "unit": "kg"},
            {"id": 14, "name": "Vega Protein Powder", "description": "Plant-based chocolate protein powder for vegan fitness enthusiasts.", "price": 2771.16 / 0.726, "unit": "kg"},
            {"id": 15, "name": "Premier Protein Shake", "description": "Vanilla shake with 30g protein, low sugar, for post-workout recovery.", "price": 231 / 0.326, "unit": "kg"},
            {"id": 201, "name": "MyProtein Impact Whey", "description": "Strawberry-flavored whey protein for muscle growth.", "price": 2399.16 / 0.900, "unit": "kg"},
            {"id": 202, "name": "Skratch Labs Hydration Mix", "description": "Lemon-lime hydration mix for optimal electrolyte balance.", "price": 149.50 / 0.454, "unit": "kg"},
            {"id": 203, "name": "Luna Protein Bar", "description": "Mint chocolate chip bar, high protein for recovery.", "price": 130 / 0.045, "unit": "kg"},
            {"id": 204, "name": "Hammer Nutrition Gel", "description": "Apple-cinnamon gel for quick energy during workouts.", "price": 140 / 0.033, "unit": "kg"},
            {"id": 205, "name": "BSN Syntha-6 Protein", "description": "Chocolate milkshake protein powder for post-workout.", "price": 2599.16 / 0.900, "unit": "kg"}
        ]
    },
    {
        "name": "Snacks",
        "items": [
            {"id": 16, "name": "Lay’s Classic Potato Chips", "description": "Crispy potato chips with a classic salted flavor, perfect for snacking.", "price": 335.31, "unit": "pack"},
            {"id": 17, "name": "Doritos Nacho Cheese", "description": "Bold nacho cheese-flavored tortilla chips, great for parties.", "price": 360.25, "unit": "pack"},
            {"id": 18, "name": "Cheetos Crunchy", "description": "Crunchy cheese-flavored puffs, a fun and tasty snack.", "price": 318.12, "unit": "pack"},
            {"id": 19, "name": "Pringles Original", "description": "Stackable potato chips with a unique original flavor.", "price": 209.03, "unit": "pack"},
            {"id": 20, "name": "Tostitos Tortilla Chips", "description": "Corn tortilla chips, ideal for dipping with salsa or guacamole.", "price": 351.94, "unit": "pack"},
            {"id": 21, "name": "Planters Mixed Nuts", "description": "A mix of peanuts, almonds, and cashews, lightly salted.", "price": 503.12, "unit": "pack"},
            {"id": 22, "name": "Blue Diamond Almonds", "description": "Roasted and salted almonds, a healthy and crunchy snack.", "price": 628.79, "unit": "pack"},
            {"id": 23, "name": "Sun-Maid Raisins", "description": "Sweet and chewy raisins, perfect for snacking or baking.", "price": 360.05, "unit": "pack"},
            {"id": 24, "name": "Oreo Cookies", "description": "Classic chocolate sandwich cookies with creamy filling.", "price": 418.71, "unit": "pack"},
            {"id": 25, "name": "Chips Ahoy! Cookies", "description": "Chocolate chip cookies, crispy and delicious.", "price": 326.78, "unit": "pack"},
            {"id": 26, "name": "Goldfish Crackers", "description": "Cheddar-flavored fish-shaped crackers, fun for kids and adults.", "price": 234.12, "unit": "pack"},
            {"id": 27, "name": "Ritz Crackers", "description": "Buttery, flaky crackers, great with cheese or spreads.", "price": 417.82, "unit": "pack"},
            {"id": 28, "name": "Triscuit Crackers", "description": "Whole grain wheat crackers, perfect for healthy snacking.", "price": 293.06, "unit": "pack"},
            {"id": 29, "name": "SkinnyPop Popcorn", "description": "Light and airy popcorn, low-calorie and gluten-free.", "price": 276.63, "unit": "pack"},
            {"id": 30, "name": "Act II Microwave Popcorn", "description": "Butter-flavored popcorn for quick and easy movie nights.", "price": 377.04, "unit": "pack"},
            {"id": 31, "name": "Rice Krispies Treats", "description": "Chewy marshmallow and rice cereal bars, a sweet treat.", "price": 267.87, "unit": "pack"},
            {"id": 32, "name": "Nature Valley Granola Bars", "description": "Oats and honey granola bars, crunchy and wholesome.", "price": 360.00, "unit": "pack"},
            {"id": 33, "name": "Chex Mix Traditional", "description": "Savory mix of cereal, pretzels, and nuts, perfect for snacking.", "price": 301.32, "unit": "pack"},
            {"id": 34, "name": "Gardetto’s Snack Mix", "description": "Zesty mix of rye chips, pretzels, and seasonings.", "price": 309.88, "unit": "pack"},
            {"id": 35, "name": "Pepperidge Farm Goldfish", "description": "Extra-large pack of cheddar Goldfish crackers, great for sharing.", "price": 838.95, "unit": "pack"},
            {"id": 36, "name": "Hershey’s Milk Chocolate", "description": "Smooth milk chocolate bars, perfect for a sweet indulgence.", "price": 460.79, "unit": "pack"},
            {"id": 37, "name": "Snickers Candy Bar", "description": "Peanuts, caramel, and chocolate in a satisfying candy bar.", "price": 108.44, "unit": "pack"},
            {"id": 38, "name": "M&M’s Peanut", "description": "Peanut-filled chocolate candies, colorful and crunchy.", "price": 402.08, "unit": "pack"},
            {"id": 39, "name": "Reese’s Peanut Butter Cups", "description": "Creamy peanut butter in milk chocolate cups, a classic treat.", "price": 443.54, "unit": "pack"},
            {"id": 40, "name": "Twizzlers Licorice", "description": "Chewy strawberry-flavored licorice twists, fun to eat.", "price": 284.66, "unit": "pack"},
            {"id": 41, "name": "Haribo Gummy Bears", "description": "Soft and fruity gummy bears, a favorite for all ages.", "price": 167.13, "unit": "pack"},
            {"id": 42, "name": "True Elements Chia Seeds", "description": "Nutrient-rich chia seeds, great for smoothies and baking.", "price": 588.00, "unit": "pack"},
            {"id": 43, "name": "Vedaka Whole Cashews", "description": "Premium whole cashews, perfect for snacking or cooking.", "price": 462.00, "unit": "pack"},
            {"id": 44, "name": "Sunfeast Farmlite Biscuits", "description": "Healthy digestive biscuits, ideal with tea or coffee.", "price": 672.00, "unit": "pack"},
            {"id": 45, "name": "Paper Boat Chikki Peanut Bar", "description": "Traditional peanut chikki, sweet and crunchy.", "price": 544.80, "unit": "pack"},
            {"id": 46, "name": "Wonder Crème Confetti Cakes", "description": "Soft cakes with creamy filling and colorful sprinkles.", "price": 292.25, "unit": "pack"},
            {"id": 47, "name": "Great Value Peanut Butter Pretzels", "description": "Pretzels filled with creamy peanut butter, a savory snack.", "price": 500.48, "unit": "pack"},
            {"id": 48, "name": "Orion Rice Crackers", "description": "Light and crispy rice crackers, mildly flavored.", "price": 419.20, "unit": "pack"},
            {"id": 49, "name": "Fruit Roll-Ups Variety Pack", "description": "Chewy fruit-flavored roll-ups, fun for kids.", "price": 359.97, "unit": "pack"},
            {"id": 50, "name": "gimMe Seaweed Sheets", "description": "Roasted seaweed sheets with sea salt, a healthy snack.", "price": 504.00, "unit": "pack"},
            {"id": 51, "name": "Kellogg’s Corn Pops", "description": "Sweet corn cereal, crunchy and kid-friendly.", "price": 418.71, "unit": "pack"},
            {"id": 52, "name": "Nature’s Path Granola", "description": "Organic granola with nuts and seeds, perfect for yogurt.", "price": 502.74, "unit": "pack"},
            {"id": 53, "name": "Pop Tarts (Strawberry)", "description": "Toasted pastries with strawberry filling, great for breakfast.", "price": 335.31, "unit": "pack"},
            {"id": 54, "name": "Clif Shot Energy Gel", "description": "Quick-energy gel with mocha flavor, boosts performance.", "price": 151.20, "unit": "pack"},
            {"id": 55, "name": "Sunchips Original", "description": "Whole grain chips with a mild, savory flavor.", "price": 293.06, "unit": "pack"}
        ]
    },
    {
        "name": "Fresh Produce",
        "items": [
            {"id": 66, "name": "Apples (Gala)", "description": "Sweet and crisp Gala apples, perfect for snacking or baking.", "price": 246, "unit": "kg"},
            {"id": 67, "name": "Bananas", "description": "Ripe yellow bananas, rich in potassium, great for smoothies.", "price": 109, "unit": "kg"},
            {"id": 68, "name": "Oranges (Naval)", "description": "Juicy naval oranges, high in vitamin C, ideal for juicing.", "price": 265, "unit": "kg"},
            {"id": 69, "name": "Strawberries", "description": "Fresh red strawberries, sweet and perfect for desserts.", "price": 647, "unit": "kg"},
            {"id": 70, "name": "Blueberries", "description": "Antioxidant-rich blueberries, great for smoothies or yogurt.", "price": 987, "unit": "kg"},
            {"id": 71, "name": "Grapes (Red Seedless)", "description": "Sweet and juicy red grapes, perfect for snacking.", "price": 555, "unit": "kg"},
            {"id": 72, "name": "Watermelon (Mini)", "description": "Refreshing mini watermelon, ideal for summer picnics.", "price": 210, "unit": "kg"},
            {"id": 73, "name": "Pineapple", "description": "Tropical pineapple, sweet and tangy, great for grilling.", "price": 184, "unit": "kg"},
            {"id": 74, "name": "Avocados (Hass)", "description": "Creamy Hass avocados, perfect for guacamole or toast.", "price": 834, "unit": "kg"},
            {"id": 75, "name": "Broccoli", "description": "Nutrient-packed broccoli, great for steaming or stir-frying.", "price": 425, "unit": "kg"},
            {"id": 76, "name": "Carrots (Baby)", "description": "Sweet baby carrots, ideal for snacking or roasting.", "price": 332, "unit": "kg"},
            {"id": 77, "name": "Tomatoes (Roma)", "description": "Firm Roma tomatoes, perfect for sauces and salads.", "price": 314, "unit": "kg"},
            {"id": 78, "name": "Cucumbers", "description": "Crisp cucumbers, great for salads or pickling.", "price": 249, "unit": "kg"},
            {"id": 79, "name": "Spinach", "description": "Fresh spinach leaves, rich in iron, ideal for smoothies.", "price": 739, "unit": "kg"},
            {"id": 80, "name": "Lettuce (Iceberg)", "description": "Crisp iceberg lettuce, perfect for sandwiches and salads.", "price": 334, "unit": "kg"},
            {"id": 81, "name": "Onions (Yellow)", "description": "Versatile yellow onions, essential for cooking and grilling.", "price": 185, "unit": "kg"},
            {"id": 82, "name": "Potatoes (Russet)", "description": "Starchy russet potatoes, ideal for baking or mashing.", "price": 129, "unit": "kg"},
            {"id": 83, "name": "Bell Peppers (Red)", "description": "Sweet red bell peppers, great for roasting or stuffing.", "price": 542, "unit": "kg"},
            {"id": 84, "name": "Zucchini", "description": "Tender zucchini, perfect for grilling or baking.", "price": 332, "unit": "kg"},
            {"id": 85, "name": "Mushrooms (White)", "description": "Fresh white mushrooms, ideal for soups and stir-fries.", "price": 811, "unit": "kg"},
            {"id": 216, "name": "Kale", "description": "Nutrient-dense kale, perfect for salads or smoothies.", "price": 650, "unit": "kg"},
            {"id": 217, "name": "Cauliflower", "description": "Versatile cauliflower, great for roasting or mashing.", "price": 420, "unit": "kg"},
            {"id": 218, "name": "Bell Peppers (Yellow)", "description": "Sweet yellow bell peppers, ideal for salads or stir-fries.", "price": 550, "unit": "kg"},
            {"id": 219, "name": "Mangoes", "description": "Juicy mangoes, perfect for smoothies or desserts.", "price": 780, "unit": "kg"},
            {"id": 220, "name": "Kiwi", "description": "Tart and sweet kiwi, great for snacking or smoothies.", "price": 950, "unit": "kg"},
            {"id": 221, "name": "Asparagus", "description": "Tender asparagus spears, ideal for grilling or steaming.", "price": 890, "unit": "kg"},
            {"id": 222, "name": "Pears (Bartlett)", "description": "Sweet Bartlett pears, perfect for eating fresh or baking.", "price": 340, "unit": "kg"},
            {"id": 223, "name": "Eggplant", "description": "Firm eggplant, great for grilling or making ratatouille.", "price": 310, "unit": "kg"}
        ]
    },
    {
        "name": "Dairy & Eggs",
        "items": [
            {"id": 86, "name": "Whole Milk", "description": "Creamy whole milk, perfect for drinking or cooking.", "price": 84, "unit": "L"},
            {"id": 87, "name": "2% Milk", "description": "Reduced-fat milk, great for cereal or coffee.", "price": 82, "unit": "L"},
            {"id": 88, "name": "Almond Milk (Silk)", "description": "Plant-based almond milk, ideal for vegan diets.", "price": 155, "unit": "L"},
            {"id": 89, "name": "Cheddar Cheese (Shredded)", "description": "Sharp cheddar cheese, perfect for melting or snacking.", "price": 1106, "unit": "kg"},
            {"id": 90, "name": "Mozzarella Cheese (Shredded)", "description": "Soft mozzarella, ideal for pizzas and pastas.", "price": 1070, "unit": "kg"},
            {"id": 91, "name": "Parmesan Cheese (Grated)", "description": "Aged Parmesan, great for grating over dishes.", "price": 1478, "unit": "kg"},
            {"id": 92, "name": "Greek Yogurt (Chobani)", "description": "Thick Greek yogurt, high in protein, great for breakfast.", "price": 722, "unit": "kg"},
            {"id": 93, "name": "Butter (Salted)", "description": "Rich salted butter, perfect for baking or spreading.", "price": 833, "unit": "kg"},
            {"id": 94, "name": "Cream Cheese (Philadelphia)", "description": "Smooth cream cheese, ideal for bagels or dips.", "price": 1181, "unit": "kg"},
            {"id": 95, "name": "Sour Cream", "description": "Creamy sour cream, great for tacos or baking.", "price": 425, "unit": "kg"},
            {"id": 96, "name": "Large Eggs", "description": "Fresh large eggs, versatile for cooking and baking.", "price": 461, "unit": "kg"},
            {"id": 97, "name": "Heavy Cream", "description": "Rich heavy cream, perfect for sauces or desserts.", "price": 620, "unit": "L"},
            {"id": 98, "name": "Cottage Cheese", "description": "Creamy cottage cheese, great for snacks or salads.", "price": 517, "unit": "kg"},
            {"id": 99, "name": "Yogurt (Yoplait)", "description": "Fruit-flavored yogurt, smooth and delicious.", "price": 440, "unit": "kg"},
            {"id": 100, "name": "Half & Half", "description": "Blend of milk and cream, ideal for coffee or cooking.", "price": 266, "unit": "L"},
            {"id": 224, "name": "Goat Cheese", "description": "Tangy goat cheese, perfect for salads or spreading.", "price": 1350, "unit": "kg"},
            {"id": 225, "name": "Oat Milk (Oatly)", "description": "Creamy oat milk, great for coffee or cereal.", "price": 160, "unit": "L"},
            {"id": 226, "name": "Feta Cheese", "description": "Crumbly feta, ideal for Mediterranean dishes.", "price": 1200, "unit": "kg"},
            {"id": 227, "name": "Whipped Cream", "description": "Sweet whipped cream, perfect for desserts.", "price": 650, "unit": "L"},
            {"id": 228, "name": "Soy Milk (Silk)", "description": "Smooth soy milk, a dairy-free alternative.", "price": 145, "unit": "L"}
        ]
    },
    {
        "name": "Meat & Seafood",
        "items": [
            {"id": 101, "name": "Chicken Breast (Boneless)", "description": "Lean boneless chicken breast, perfect for grilling or baking.", "price": 789, "unit": "kg"},
            {"id": 102, "name": "Ground Beef (80/20)", "description": "80% lean ground beef, ideal for burgers or meatballs.", "price": 912, "unit": "kg"},
            {"id": 103, "name": "Pork Chops (Bone-In)", "description": "Juicy bone-in pork chops, great for pan-searing.", "price": 834, "unit": "kg"},
            {"id": 104, "name": "Salmon Fillet (Atlantic)", "description": "Fresh Atlantic salmon fillet, rich in omega-3, perfect for baking.", "price": 1899, "unit": "kg"},
            {"id": 105, "name": "Shrimp (Peeled)", "description": "Peeled and deveined shrimp, ideal for stir-fries or grilling.", "price": 1659, "unit": "kg"},
            {"id": 106, "name": "Bacon (Thick-Cut)", "description": "Thick-cut bacon, smoky and crispy, great for breakfast.", "price": 1259, "unit": "kg"},
            {"id": 107, "name": "Chicken Thighs (Boneless)", "description": "Tender boneless chicken thighs, perfect for marinating.", "price": 678, "unit": "kg"},
            {"id": 108, "name": "Beef Steak (Ribeye)", "description": "Marbled ribeye steak, ideal for grilling or pan-searing.", "price": 2319, "unit": "kg"},
            {"id": 109, "name": "Turkey Breast", "description": "Lean turkey breast, great for roasting or sandwiches.", "price": 912, "unit": "kg"},
            {"id": 110, "name": "Cod Fillet", "description": "Mild-flavored cod fillet, perfect for baking or frying.", "price": 1559, "unit": "kg"},
            {"id": 229, "name": "Lamb Chops", "description": "Tender lamb chops, ideal for grilling or roasting.", "price": 2200, "unit": "kg"},
            {"id": 230, "name": "Tuna Steak", "description": "Fresh tuna steak, great for searing or grilling.", "price": 1950, "unit": "kg"},
            {"id": 231, "name": "Chicken Wings", "description": "Juicy chicken wings, perfect for frying or baking.", "price": 650, "unit": "kg"},
            {"id": 232, "name": "Beef Brisket", "description": "Flavorful beef brisket, ideal for slow cooking.", "price": 1400, "unit": "kg"},
            {"id": 233, "name": "Tilapia Fillet", "description": "Mild tilapia fillet, great for light dishes.", "price": 1200, "unit": "kg"}
        ]
    },
    {
        "name": "Bakery",
        "items": [
            {"id": 111, "name": "White Bread (Sliced)", "description": "Soft sliced white bread, perfect for sandwiches.", "price": 209, "unit": "pack"},
            {"id": 112, "name": "Whole Wheat Bread", "description": "Healthy whole wheat bread, great for toasting.", "price": 234, "unit": "pack"},
            {"id": 113, "name": "Bagels (Plain)", "description": "Chewy plain bagels, ideal for breakfast with cream cheese.", "price": 418, "unit": "pack"},
            {"id": 114, "name": "Croissants", "description": "Buttery and flaky croissants, perfect for a light breakfast.", "price": 838, "unit": "pack"},
            {"id": 115, "name": "Muffins (Blueberry)", "description": "Moist blueberry muffins, great for a quick snack.", "price": 586, "unit": "pack"},
            {"id": 116, "name": "Sourdough Bread", "description": "Tangy sourdough bread, ideal for artisanal sandwiches.", "price": 377, "unit": "pack"},
            {"id": 117, "name": "Dinner Rolls", "description": "Soft dinner rolls, perfect for family dinners.", "price": 293, "unit": "pack"},
            {"id": 118, "name": "Donuts (Glazed)", "description": "Sweet glazed donuts, a classic treat.", "price": 586, "unit": "pack"},
            {"id": 119, "name": "Ciabatta Bread", "description": "Rustic ciabatta bread, great for sandwiches or dipping.", "price": 335, "unit": "pack"},
            {"id": 120, "name": "Cinnamon Rolls", "description": "Sweet cinnamon rolls with icing, perfect for dessert.", "price": 670, "unit": "pack"},
            {"id": 234, "name": "Rye Bread", "description": "Hearty rye bread, ideal for deli sandwiches.", "price": 280, "unit": "pack"},
            {"id": 235, "name": "Pita Bread", "description": "Soft pita bread, perfect for wraps or dipping.", "price": 250, "unit": "pack"},
            {"id": 236, "name": "Banana Bread", "description": "Moist banana bread, great for breakfast or snacks.", "price": 400, "unit": "pack"},
            {"id": 237, "name": "Brioche Buns", "description": "Rich brioche buns, ideal for gourmet burgers.", "price": 500, "unit": "pack"},
            {"id": 238, "name": "Chocolate Chip Cookies", "description": "Freshly baked chocolate chip cookies, soft and chewy.", "price": 450, "unit": "pack"}
        ]
    },
    {
        "name": "Beverages",
        "items": [
            {"id": 121, "name": "Coca-Cola (2L)", "description": "Refreshing cola drink, perfect for sharing.", "price": 159, "unit": "bottle"},
            {"id": 122, "name": "Pepsi (2L)", "description": "Bold and refreshing Pepsi, great for parties.", "price": 159, "unit": "bottle"},
            {"id": 123, "name": "Sprite (2L)", "description": "Lemon-lime flavored soda, crisp and refreshing.", "price": 159, "unit": "bottle"},
            {"id": 124, "name": "Orange Juice (Tropicana)", "description": "100% pure orange juice, rich in vitamin C.", "price": 335, "unit": "bottle"},
            {"id": 125, "name": "Apple Juice (Minute Maid)", "description": "Sweet apple juice, great for kids and adults.", "price": 293, "unit": "bottle"},
            {"id": 126, "name": "Bottled Water (Dasani)", "description": "Purified bottled water, perfect for hydration.", "price": 84, "unit": "bottle"},
            {"id": 127, "name": "Sparkling Water (Perrier)", "description": "Carbonated mineral water, refreshing and crisp.", "price": 209, "unit": "bottle"},
            {"id": 128, "name": "Iced Tea (Lipton)", "description": "Lemon-flavored iced tea, refreshing and sweet.", "price": 251, "unit": "bottle"},
            {"id": 129, "name": "Green Tea (Pure Leaf)", "description": "Unsweetened green tea, packed with antioxidants.", "price": 293, "unit": "bottle"},
            {"id": 130, "name": "Energy Drink (Red Bull)", "description": "Classic energy drink, boosts energy and focus.", "price": 209, "unit": "can"},
            {"id": 239, "name": "Lemonade (Simply)", "description": "Freshly squeezed lemonade, sweet and tangy.", "price": 300, "unit": "bottle"},
            {"id": 240, "name": "Coconut Water (Vita Coco)", "description": "Pure coconut water, hydrating and refreshing.", "price": 250, "unit": "bottle"},
            {"id": 241, "name": "Ginger Ale (Canada Dry)", "description": "Crisp ginger ale, great for mixing or sipping.", "price": 160, "unit": "bottle"},
            {"id": 242, "name": "Cranberry Juice (Ocean Spray)", "description": "Tart cranberry juice, rich in antioxidants.", "price": 320, "unit": "bottle"},
            {"id": 243, "name": "Kombucha (GT’s)", "description": "Fermented tea drink, supports gut health.", "price": 400, "unit": "bottle"}
        ]
    },
    {
        "name": "Cooking Essentials",
        "items": [
            {"id": 186, "name": "Olive Oil (Extra Virgin)", "description": "Premium extra virgin olive oil, ideal for cooking or dressings.", "price": 896, "unit": "L"},
            {"id": 187, "name": "Canola Oil", "description": "Neutral-flavored canola oil, great for frying or baking.", "price": 295, "unit": "L"},
            {"id": 188, "name": "Vegetable Oil", "description": "Versatile vegetable oil, perfect for all-purpose cooking.", "price": 266, "unit": "L"},
            {"id": 189, "name": "All-Purpose Flour", "description": "Fine all-purpose flour, essential for baking and cooking.", "price": 111, "unit": "kg"},
            {"id": 190, "name": "Granulated Sugar", "description": "Pure white sugar, ideal for baking or sweetening.", "price": 162, "unit": "kg"},
            {"id": 191, "name": "Brown Sugar", "description": "Moist brown sugar, great for cookies or sauces.", "price": 212, "unit": "kg"},
            {"id": 192, "name": "Baking Powder", "description": "Double-acting baking powder, essential for baking.", "price": 731, "unit": "kg"},
            {"id": 193, "name": "Baking Soda", "description": "Pure baking soda, great for baking or cleaning.", "price": 239, "unit": "kg"},
            {"id": 194, "name": "Vanilla Extract", "description": "Pure vanilla extract, adds rich flavor to desserts.", "price": 4266, "unit": "L"},
            {"id": 195, "name": "Cocoa Powder", "description": "Unsweetened cocoa powder, perfect for chocolate desserts.", "price": 1291, "unit": "kg"},
            {"id": 196, "name": "Salt (Table)", "description": "Fine table salt, essential for seasoning.", "price": 136, "unit": "kg"},
            {"id": 197, "name": "Black Pepper (Ground)", "description": "Ground black pepper, adds spice to any dish.", "price": 2460, "unit": "kg"},
            {"id": 198, "name": "Garlic Powder", "description": "Granulated garlic powder, perfect for seasoning.", "price": 2005, "unit": "kg"},
            {"id": 199, "name": "Onion Powder", "description": "Fine onion powder, great for soups or rubs.", "price": 2490, "unit": "kg"},
            {"id": 200, "name": "Paprika", "description": "Smoky paprika, adds color and flavor to dishes.", "price": 3360, "unit": "kg"},
            {"id": 256, "name": "Coconut Oil", "description": "Pure coconut oil, ideal for cooking or baking.", "price": 920, "unit": "L"},
            {"id": 257, "name": "Honey", "description": "Natural honey, perfect for sweetening or baking.", "price": 1100, "unit": "kg"},
            {"id": 258, "name": "Cinnamon (Ground)", "description": "Warm ground cinnamon, great for baking or oatmeal.", "price": 2800, "unit": "kg"},
            {"id": 259, "name": "Soy Sauce", "description": "Savory soy sauce, ideal for Asian dishes.", "price": 450, "unit": "L"},
            {"id": 260, "name": "Chili Powder", "description": "Spicy chili powder, perfect for seasoning meats.", "price": 3100, "unit": "kg"}
        ]
    },
    {
        "name": "Cleaning Supplies",
        "items": [
            {"id": 261, "name": "Dish Soap (Dawn)", "description": "Powerful dish soap, cuts through grease easily.", "price": 350, "unit": "L"},
            {"id": 262, "name": "Laundry Detergent (Tide)", "description": "Effective detergent, removes tough stains.", "price": 800, "unit": "L"},
            {"id": 263, "name": "All-Purpose Cleaner (Lysol)", "description": "Versatile cleaner, disinfects surfaces.", "price": 450, "unit": "L"},
            {"id": 264, "name": "Glass Cleaner (Windex)", "description": "Streak-free glass cleaner, shines windows.", "price": 400, "unit": "L"},
            {"id": 265, "name": "Sponges (Scotch-Brite)", "description": "Durable sponges, great for scrubbing dishes.", "price": 250, "unit": "pack"},
            {"id": 266, "name": "Trash Bags (Glad)", "description": "Strong trash bags, prevents leaks.", "price": 600, "unit": "pack"},
            {"id": 267, "name": "Bleach (Clorox)", "description": "Powerful bleach, disinfects and whitens.", "price": 500, "unit": "L"},
            {"id": 268, "name": "Dishwasher Pods (Cascade)", "description": "Convenient pods, cleans dishes thoroughly.", "price": 700, "unit": "pack"},
            {"id": 269, "name": "Fabric Softener (Downy)", "description": "Softens clothes, leaves a fresh scent.", "price": 650, "unit": "L"},
            {"id": 270, "name": "Air Freshener (Febreze)", "description": "Odor-eliminating spray, fresh linen scent.", "price": 300, "unit": "pack"}
        ]
    },
    {
        "name": "Miscellaneous",
        "items": [
            {"id": 271, "name": "AA Batteries (Energizer)", "description": "Long-lasting AA batteries, great for devices.", "price": 500, "unit": "pack"},
            {"id": 272, "name": "Paper Towels (Bounty)", "description": "Absorbent paper towels, perfect for spills.", "price": 450, "unit": "pack"},
            {"id": 273, "name": "Toilet Paper (Charmin)", "description": "Soft toilet paper, strong and absorbent.", "price": 600, "unit": "pack"},
            {"id": 274, "name": "Aluminum Foil (Reynolds)", "description": "Durable foil, ideal for cooking or storage.", "price": 350, "unit": "pack"},
            {"id": 275, "name": "Plastic Wrap (Saran)", "description": "Cling wrap, keeps food fresh.", "price": 300, "unit": "pack"},
            {"id": 276, "name": "Ziploc Bags (Gallon)", "description": "Resealable bags, great for storage.", "price": 400, "unit": "pack"},
            {"id": 277, "name": "Light Bulbs (Philips)", "description": "Energy-efficient LED bulbs, bright light.", "price": 550, "unit": "pack"},
            {"id": 278, "name": "Duct Tape (3M)", "description": "Strong duct tape, versatile for repairs.", "price": 250, "unit": "pack"},
            {"id": 279, "name": "Candles (Yankee)", "description": "Scented candles, vanilla aroma.", "price": 700, "unit": "pack"},
            {"id": 280, "name": "Matches (Diamond)", "description": "Wooden matches, easy to light.", "price": 100, "unit": "pack"}
        ]
    },
    {
        "name": "Books",
        "items": [
            {"id": 281, "name": "Sapiens: A Brief History", "description": "Exploration of human history by Yuval Noah Harari.", "price": 499, "unit": "unit"},
            {"id": 282, "name": "Atomic Habits", "description": "Guide to building good habits by James Clear.", "price": 599, "unit": "unit"},
            {"id": 283, "name": "The Alchemist", "description": "Paulo Coelho's tale of self-discovery.", "price": 299, "unit": "unit"},
            {"id": 284, "name": "1984", "description": "George Orwell's dystopian novel.", "price": 249, "unit": "unit"},
            {"id": 285, "name": "Thinking, Fast and Slow", "description": "Daniel Kahneman's insights on decision-making.", "price": 499, "unit": "unit"},
            {"id": 286, "name": "The Power of Now", "description": "Eckhart Tolle's guide to mindfulness.", "price": 399, "unit": "unit"},
            {"id": 287, "name": "Dune", "description": "Frank Herbert's sci-fi epic.", "price": 599, "unit": "unit"},
            {"id": 288, "name": "The Subtle Art", "description": "Mark Manson's self-help book.", "price": 449, "unit": "unit"},
            {"id": 289, "name": "Educated", "description": "Tara Westover's memoir of self-education.", "price": 499, "unit": "unit"},
            {"id": 290, "name": "The Hobbit", "description": "J.R.R. Tolkien's fantasy adventure.", "price": 349, "unit": "unit"}
        ]
    },
    {
        "name": "Ice Creams",
        "items": [
            {"id": 291, "name": "Amul Vanilla Ice Cream", "description": "Classic creamy vanilla ice cream.", "price": 150, "unit": "L"},
            {"id": 292, "name": "Baskin Robbins Chocolate", "description": "Rich chocolate ice cream.", "price": 300, "unit": "L"},
            {"id": 293, "name": "Häagen-Dazs Strawberry", "description": "Sweet strawberry ice cream with real fruit.", "price": 350, "unit": "L"},
            {"id": 294, "name": "Kwality Walls Mango", "description": "Tropical mango ice cream.", "price": 200, "unit": "L"},
            {"id": 295, "name": "Ben & Jerry’s Cookie Dough", "description": "Vanilla with cookie dough chunks.", "price": 400, "unit": "L"},
            {"id": 296, "name": "Amul Butterscotch", "description": "Butterscotch ice cream with caramel bits.", "price": 180, "unit": "L"},
            {"id": 297, "name": "Cornetto Chocolate Cone", "description": "Chocolate ice cream in a crispy cone.", "price": 50, "unit": "unit"},
            {"id": 298, "name": "Magnum Classic", "description": "Vanilla ice cream with chocolate coating.", "price": 80, "unit": "unit"},
            {"id": 299, "name": "Breyers Natural Vanilla", "description": "Pure vanilla ice cream.", "price": 250, "unit": "L"},
            {"id": 300, "name": "Mother Dairy Pista Kulfi", "description": "Pistachio-flavored kulfi.", "price": 60, "unit": "unit"}
        ]
    },
    {
        "name": "Personal Care",
        "items": [
            {"id": 301, "name": "Shampoo (Dove)", "description": "Moisturizing shampoo for smooth hair.", "price": 300, "unit": "pack"},
            {"id": 302, "name": "Conditioner (Pantene)", "description": "Nourishing conditioner for healthy hair.", "price": 320, "unit": "pack"},
            {"id": 303, "name": "Body Wash (Nivea)", "description": "Hydrating body wash for soft skin.", "price": 250, "unit": "pack"},
            {"id": 304, "name": "Toothpaste (Colgate)", "description": "Cavity protection toothpaste.", "price": 150, "unit": "pack"},
            {"id": 305, "name": "Deodorant (Old Spice)", "description": "Long-lasting deodorant stick.", "price": 200, "unit": "pack"},
            {"id": 306, "name": "Face Wash (Cetaphil)", "description": "Gentle facial cleanser for all skin types.", "price": 400, "unit": "pack"},
            {"id": 307, "name": "Hand Soap (Dove)", "description": "Moisturizing liquid hand soap.", "price": 180, "unit": "pack"},
            {"id": 308, "name": "Razor Blades (Gillette)", "description": "5-blade razor refills for a close shave.", "price": 500, "unit": "pack"},
            {"id": 309, "name": "Moisturizer (Olay)", "description": "Hydrating face cream for daily use.", "price": 350, "unit": "pack"},
            {"id": 310, "name": "Sunscreen (SPF 50)", "description": "Broad-spectrum sunscreen for UV protection.", "price": 400, "unit": "pack"}
        ]
    },
    {
        "name": "Frozen Foods",
        "items": [
            {"id": 311, "name": "Frozen Pizza (Pepperoni)", "description": "Pepperoni pizza, ready to bake.", "price": 600, "unit": "pack"},
            {"id": 312, "name": "Frozen French Fries", "description": "Crispy potato fries for quick meals.", "price": 250, "unit": "kg"},
            {"id": 313, "name": "Chicken Nuggets", "description": "Breaded chicken nuggets, kid-friendly.", "price": 400, "unit": "kg"},
            {"id": 314, "name": "Veggie Burger Patties", "description": "Plant-based burger patties.", "price": 350, "unit": "pack"},
            {"id": 315, "name": "Frozen Peas", "description": "Sweet green peas, perfect for sides.", "price": 200, "unit": "kg"},
            {"id": 316, "name": "Fish Sticks", "description": "Breaded fish sticks, easy to prepare.", "price": 500, "unit": "kg"},
            {"id": 317, "name": "Mixed Vegetables", "description": "Frozen mix of carrots, peas, corn.", "price": 220, "unit": "kg"},
            {"id": 318, "name": "Ice Cream Sandwiches", "description": "Vanilla ice cream between chocolate wafers.", "price": 300, "unit": "pack"},
            {"id": 319, "name": "Frozen Paratha", "description": "Indian flatbread, ready to cook.", "price": 200, "unit": "pack"},
            {"id": 320, "name": "Chicken Wings", "description": "Spicy frozen chicken wings.", "price": 450, "unit": "kg"}
        ]
    }
]